/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppConfirm: typeof import('./src/components/common/AppConfirm.vue')['default']
    AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/common/AppInput.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppModal: typeof import('./src/components/common/AppModal.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppSpinner: typeof import('./src/components/common/AppSpinner.vue')['default']
    AppTextarea: typeof import('./src/components/common/AppTextarea.vue')['default']
    AppToast: typeof import('./src/components/common/AppToast.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    NovelWorkspaceTabs: typeof import('./src/components/novels/NovelWorkspaceTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WritingEditor: typeof import('./src/components/editor/WritingEditor.vue')['default']
  }
}

// For TSX support
declare global {
  const AppButton: typeof import('./src/components/common/AppButton.vue')['default']
  const AppCard: typeof import('./src/components/common/AppCard.vue')['default']
  const AppConfirm: typeof import('./src/components/common/AppConfirm.vue')['default']
  const AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
  const AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
  const AppInput: typeof import('./src/components/common/AppInput.vue')['default']
  const AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
  const AppModal: typeof import('./src/components/common/AppModal.vue')['default']
  const AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
  const AppSpinner: typeof import('./src/components/common/AppSpinner.vue')['default']
  const AppTextarea: typeof import('./src/components/common/AppTextarea.vue')['default']
  const AppToast: typeof import('./src/components/common/AppToast.vue')['default']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElText: typeof import('element-plus/es')['ElText']
  const NovelWorkspaceTabs: typeof import('./src/components/novels/NovelWorkspaceTabs.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WritingEditor: typeof import('./src/components/editor/WritingEditor.vue')['default']
}