/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppConfirm: typeof import('./src/components/common/AppConfirm.vue')['default']
    AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/common/AppInput.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppModal: typeof import('./src/components/common/AppModal.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppSpinner: typeof import('./src/components/common/AppSpinner.vue')['default']
    AppTextarea: typeof import('./src/components/common/AppTextarea.vue')['default']
    AppToast: typeof import('./src/components/common/AppToast.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    NovelWorkspaceTabs: typeof import('./src/components/novels/NovelWorkspaceTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WritingEditor: typeof import('./src/components/editor/WritingEditor.vue')['default']
  }
}

// For TSX support
declare global {
  const AppButton: typeof import('./src/components/common/AppButton.vue')['default']
  const AppCard: typeof import('./src/components/common/AppCard.vue')['default']
  const AppConfirm: typeof import('./src/components/common/AppConfirm.vue')['default']
  const AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
  const AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
  const AppInput: typeof import('./src/components/common/AppInput.vue')['default']
  const AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
  const AppModal: typeof import('./src/components/common/AppModal.vue')['default']
  const AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
  const AppSpinner: typeof import('./src/components/common/AppSpinner.vue')['default']
  const AppTextarea: typeof import('./src/components/common/AppTextarea.vue')['default']
  const AppToast: typeof import('./src/components/common/AppToast.vue')['default']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
  const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElText: typeof import('element-plus/es')['ElText']
  const NovelWorkspaceTabs: typeof import('./src/components/novels/NovelWorkspaceTabs.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WritingEditor: typeof import('./src/components/editor/WritingEditor.vue')['default']
}