"""phase_1_writing_models

Revision ID: 24610e0b6c71
Revises: 06b49c3d3da5
Create Date: 2026-06-28 02:00:47.801301

"""
from typing import Collection, Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24610e0b6c71'
down_revision: str | None = '06b49c3d3da5'
branch_labels: str | Collection[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_blueprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_blueprints_novel_id'), 'novel_blueprints', ['novel_id'], unique=False)
    op.create_table('chapter_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_plans_novel_id'), 'chapter_plans', ['novel_id'], unique=False)
    op.create_table('chapter_briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_plan_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('brief_json', sa.JSON(), nullable=False),
    sa.Column('length_contract_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['chapter_plan_id'], ['chapter_plans.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_briefs_novel_id'), 'chapter_briefs', ['novel_id'], unique=False)
    op.create_table('context_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_brief_id', sa.Integer(), nullable=False),
    sa.Column('package_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_brief_id'], ['chapter_briefs.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_packages_novel_id'), 'context_packages', ['novel_id'], unique=False)
    op.create_table('writing_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_brief_id', sa.Integer(), nullable=False),
    sa.Column('context_package_id', sa.Integer(), nullable=False),
    sa.Column('target_chapter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('gate_result_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_brief_id'], ['chapter_briefs.id'], ),
    sa.ForeignKeyConstraint(['context_package_id'], ['context_packages.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['target_chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_runs_novel_id'), 'writing_runs', ['novel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_runs_novel_id'), table_name='writing_runs')
    op.drop_table('writing_runs')
    op.drop_index(op.f('ix_context_packages_novel_id'), table_name='context_packages')
    op.drop_table('context_packages')
    op.drop_index(op.f('ix_chapter_briefs_novel_id'), table_name='chapter_briefs')
    op.drop_table('chapter_briefs')
    op.drop_index(op.f('ix_chapter_plans_novel_id'), table_name='chapter_plans')
    op.drop_table('chapter_plans')
    op.drop_index(op.f('ix_novel_blueprints_novel_id'), table_name='novel_blueprints')
    op.drop_table('novel_blueprints')
    # ### end Alembic commands ###
